In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_excel("customer churn.xlsx")

In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
dataset=pd.get_dummies(dataset,columns=['Geography','Gender'])
print(dataset.head(15))

    RowNumber  CustomerId   Surname  CreditScore  Age  Tenure    Balance  \
0           1    15634602  Hargrave          619   42       2       0.00   
1           2    15647311      Hill          608   41       1   83807.86   
2           3    15619304      Onio          502   42       8  159660.80   
3           4    15701354      Boni          699   39       1       0.00   
4           5    15737888  Mitchell          850   43       2  125510.82   
5           6    15574012       Chu          645   44       8  113755.78   
6           7    15592531  Bartlett          822   50       7       0.00   
7           8    15656148    Obinna          376   29       4  115046.74   
8           9    15792365        He          501   44       4  142051.07   
9          10    15592389        H?          684   27       2  134603.88   
10         11    15767821    Bearce          528   31       6  102016.72   
11         12    15737173   Andrews          497   24       3       0.00   
12         1

In [6]:
x=dataset.drop (columns=['Exited','Surname','RowNumber'],axis=1)
y=dataset['Exited']

In [7]:
x

CustomerId  CreditScore  Age  Tenure    Balance  NumOfProducts  \
0       15634602          619   42       2       0.00              1   
1       15647311          608   41       1   83807.86              1   
2       15619304          502   42       8  159660.80              3   
3       15701354          699   39       1       0.00              2   
4       15737888          850   43       2  125510.82              1   
...          ...          ...  ...     ...        ...            ...   
9995    15606229          771   39       5       0.00              2   
9996    15569892          516   35      10   57369.61              1   
9997    15584532          709   36       7       0.00              1   
9998    15682355          772   42       3   75075.31              2   
9999    15628319          792   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Geography_France  \
0             1               1        101348.88                 1   
1             0               1        112542.58                 0   
2             1               0        113931.57                 1   
3             0               0         93826.63                 1   
4             1               1         79084.10                 0   
...         ...             ...              ...               ...   
9995          1               0         96270.64                 1   
9996          1               1        101699.77                 1   
9997          0               1         42085.58                 1   
9998          1               0         92888.52                 0   
9999          1               0         38190.78                 1   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                     0                0              1            0  
1                     0                1              1            0  
2                     0                0              1            0  
3                     0                0              1            0  
4                     0                1              1            0  
...                 ...              ...            ...          ...  
9995                  0                0              0            1  
9996                  0                0              0            1  
9997                  0                0              1            0  
9998                  1                0              0            1  
9999                  0                0              1            0  

[10000 rows x 14 columns]

In [8]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [9]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
scaler=StandardScaler()
xtrain=scaler.fit_transform(xtrain)
xtest=scaler.fit_transform(xtest)

In [11]:
log_reg=LogisticRegression()
log_reg.fit(xtrain,ytrain)
log_predict=log_reg.predict(xtest)

In [17]:
rand_forst=RandomForestClassifier()
rand_forst.fit(xtrain,ytrain)
rand_predict=rand_forst.predict(xtest)

In [13]:
grad_boost=GradientBoostingClassifier()
grad_boost.fit(xtrain,ytrain)
grad_predict=grad_boost.predict(xtest)

In [14]:
print("Accuracy:",accuracy_score(ytest,log_predict))
print("Confusion matrix:\n",confusion_matrix(ytest,log_predict))

Accuracy: 0.8105
Confusion matrix:
 [[1540   67]
 [ 312   81]]


In [15]:
print("Accuracy",accuracy_score(ytest,rand_predict))
print("Confusion matrix:\n",confusion_matrix(ytest,rand_predict))

Accuracy 0.865
Confusion matrix:
 [[1550   57]
 [ 213  180]]


In [16]:
print("Accuracy",accuracy_score(ytest,grad_predict))
print("Confusion matrix:\n",confusion_matrix(ytest,grad_predict))

Accuracy 0.864
Confusion matrix:
 [[1539   68]
 [ 204  189]]
